name = "FLOWPanel"
uuid = "6be8c882-484d-4309-b349-d23112750151"
author = ["Eduardo Alvarez <Edo.AlvarezR@gmail.com>"]
version = "1.2.1"

[deps]
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
# FastMultipole = "ce07d0d3-2b9f-49ba-89eb-12c800257c85"
GeometricTools = "83792f5e-c6a1-11e8-2e0a-93511f02ae5f"
ImplicitAD = "e7cbb90b-9b31-4eb2-a8c8-45099c074ee1"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
FLOWMath = "6cb5d3fb-0fe8-4cc2-bd89-9fe0b19a99d3"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
AirfoilPrep = "008c61af-3522-4e14-81c5-9301d18a9f66"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
SimpleNonlinearSolve = "727e6d20-b764-4bd8-a329-72de5adea6c7"

# [sources]
# FastMultipole = {url = "https://github.com/byuflowlab/FastMultipole", rev = "d21d242d081ea8c9c19655097d83413b1f783d2d"}

[compat]
julia = "1.8"
Dierckx = "0.5"
GeometricTools = "2"
ImplicitAD = "0.3"
Krylov = "0.9"
LinearOperators = "2"
StaticArrays = "1"
WriteVTK = "1"
Requires = "1"
FLOWMath = "1"
AirfoilPrep = "2"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "Test", "Printf", "ForwardDiff", "CSV", "DataFrames"]
